name: 'Auto Diff'
description: 'Automatically get changed folders'
outputs:
  files:
    description: "The new version"
    value: ${{ steps.version-generator.outputs.files }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: version-generator
      run: chmod +x ${{ github.action_path }}/autodiff/main.py && ${{ github.action_path }}/autodiff/main.py >> "$GITHUB_OUTPUT"
      shell: bash
    - id: version-generator-print
      run: ${{ github.action_path }}/autodiff/main.py
      shell: bash
